// Generated by scripts/generate-infobubble-index.mjs — do not edit by hand.
import type { SearchEntry } from "./searchIndex";

export const infoBubbleIndex: SearchEntry[] = [
  {
    title: "Compte courant individuel",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "Compte courant joint",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  { title: "Livret A", subtitle: "Les types de comptes", to: "/accounts" },
  {
    title: "LDDS - Livret de Développement Durable et Solidaire",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "LEP - Livret d'Épargne Populaire",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  { title: "Livret Jeune", subtitle: "Les types de comptes", to: "/accounts" },
  {
    title: "PEL - Plan Épargne Logement",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "CEL - Compte Épargne Logement",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "PEA - Plan Épargne en Actions",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "PEE - Plan d'Épargne Entreprise",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "PER - Plan Épargne Retraite",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  { title: "Assurance Vie", subtitle: "Les types de comptes", to: "/accounts" },
  {
    title: "CTO - Compte-Titres Ordinaire",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "CAT - Compte à Terme",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "Livret bancaire (non réglementé)",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "PEAC - Plan Épargne Avenir Climat",
    subtitle: "Les types de comptes",
    to: "/accounts",
  },
  {
    title: "Pourquoi les banques veulent votre argent",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  {
    title: "Le cœur du modèle bancaire : prêter plus cher qu'ils n'empruntent",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  {
    title: "Les réserves fractionnaires, comment 1 € permet de prêter plus",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  {
    title: "Le rôle de la Banque centrale",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  {
    title: "Les autres sources de revenus des banques",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  {
    title: "Pourquoi une banque ne disparaît pas du jour au lendemain",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  { title: "Taux d'épargne", subtitle: "Le système bancaire", to: "/banking" },
  {
    title: "Cartes de débit & crédit",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  { title: "Frais bancaires", subtitle: "Le système bancaire", to: "/banking" },
  {
    title: "Garantie des dépôts",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  {
    title: "Sécurité des transactions",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  {
    title: "Fraudes courantes",
    subtitle: "Le système bancaire",
    to: "/banking",
  },
  {
    title: "Valeur de l'argent dans le temps, inflation et déflation",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Taux d'intérêts",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Différence revenu vs patrimoine",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Épargne vs investissement",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Risque de marché",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Risque de contrepartie",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Risque de taux",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Risque de change",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Risque de liquidité",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  { title: "Risque pays", subtitle: "Les bases de la finance", to: "/basics" },
  {
    title: "Risque opérationnel",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Risque comportemental",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  {
    title: "Risque idiosyncratique",
    subtitle: "Les bases de la finance",
    to: "/basics",
  },
  { title: "Mon Discord", subtitle: "Me contacter", to: "/contact" },
  { title: "Message envoyé !", subtitle: "Me contacter", to: "/contact" },
  { title: "Mon Discord", subtitle: "Me contacter", to: "/contact" },
  { title: "Contactez-moi", subtitle: "Me contacter", to: "/contact" },
  {
    title: "Introduction aux cryptomonnaies",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Cryptos de paiement / réserve de valeur",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Plateformes de smart contracts",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Tokens d'exchange",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  { title: "Stablecoins", subtitle: "Les cryptomonnaies", to: "/cryptos" },
  {
    title: "Cryptos axées sur la confidentialité",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Tokens utilitaires (DeFi / services)",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Cryptos d'infrastructure financière",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Hot wallets (portefeuilles en ligne)",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Cold wallets (portefeuilles hors ligne)",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Clé privée et phrase de récupération",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Risques et bonnes pratiques",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  {
    title: "Détails et conseils pour se lancer",
    subtitle: "Les cryptomonnaies",
    to: "/cryptos",
  },
  { title: "Bienvenue !", subtitle: "AmarokeInsights", to: "/" },
  { title: "À savoir", subtitle: "AmarokeInsights", to: "/" },
  { title: "Ordre conseillé", subtitle: "AmarokeInsights", to: "/" },
  { title: "Contact & retours", subtitle: "AmarokeInsights", to: "/" },
  { title: "Disclaimer", subtitle: "AmarokeInsights", to: "/" },
  {
    title: "Organigramme d'investissement",
    subtitle: "Comment investir ?",
    to: "/investments2",
  },
  {
    title: "Une enveloppe fiscale très puissante",
    subtitle: "Comment investir ?",
    to: "/investments2",
  },
  {
    title: "Les pièges à éviter",
    subtitle: "Comment investir ?",
    to: "/investments2",
  },
  {
    title: "Que choisir entre Assurance Vie et CTO ?",
    subtitle: "Comment investir ?",
    to: "/investments2",
  },
  {
    title: "L'article 111bis est-il intéressant pour les frontaliers ?",
    subtitle: "Comment investir ?",
    to: "/investments2",
  },
  {
    title: "Pourquoi investir ?",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Les trois dimensions d'un investissement",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Le couple rendement / risque, comment choisir ?",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Le DCA (Dollar Cost Averaging)",
    subtitle: "Les investissements",
    to: "/investments",
  },
  { title: "Les actions", subtitle: "Les investissements", to: "/investments" },
  {
    title: "Les ETF (Trackers)",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Les Obligations",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Les Fonds d'investissement (OPCVM, SICAV, FCP)",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Produits dérivés et structurés",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Immobilier direct",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "SCPI (Société Civile de Placement Immobilier)",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Crowdfunding immobilier",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Matières premières et métaux précieux",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Cryptoactifs et Web3",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Private Equity",
    subtitle: "Les investissements",
    to: "/investments",
  },
  { title: "Hedge Funds", subtitle: "Les investissements", to: "/investments" },
  {
    title: "Placements atypiques (art, vin, montres...)",
    subtitle: "Les investissements",
    to: "/investments",
  },
  {
    title: "Mentions légales",
    subtitle: "Mentions légales & Confidentialité",
    to: "/legal",
  },
  {
    title: "Politique de confidentialité",
    subtitle: "Mentions légales & Confidentialité",
    to: "/legal",
  },
  {
    title: "Sous-traitants",
    subtitle: "Mentions légales & Confidentialité",
    to: "/legal",
  },
  { title: "Bibliothèques open-source", subtitle: "Licences", to: "/licenses" },
  { title: "Polices de caractères", subtitle: "Licences", to: "/licenses" },
  {
    title: "Qu'est-ce qu'un budget ?",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "La méthode 50 / 30 / 20",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "Stratégie de priorités financières",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "L'épargne",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "Le fonds de secours",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "Qu'est-ce que le mouvement FIRE ?",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "Capacité d'épargne",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "Maîtriser son endettement",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "Optimiser et gérer ses emprunts",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "Emprunt levier",
    subtitle: "Finance personnelle",
    to: "/personal-finance",
  },
  {
    title: "Work in Progress",
    subtitle: "Louer ou Acheter ?",
    to: "/rent-vs-buy",
  },
  { title: "Liens utiles", subtitle: "Ressources", to: "/resources" },
  { title: "Lectures recommandées", subtitle: "Ressources", to: "/resources" },
  {
    title: "Work in Progress",
    subtitle: "Profil de risque",
    to: "/risk-profile",
  },
  {
    title: "Matelas de sécurité - Livret A",
    subtitle: "Ma stratégie personnelle",
    to: "/strategy",
  },
  {
    title: "PEA - Objectif 2030",
    subtitle: "Ma stratégie personnelle",
    to: "/strategy",
  },
  {
    title: "Trading et cryptos",
    subtitle: "Ma stratégie personnelle",
    to: "/strategy",
  },
  {
    title: "Pourquoi cette section ?",
    subtitle: "Ma stratégie personnelle",
    to: "/strategy",
  },
  {
    title: "Pourquoi viser 1 million d'euros ?",
    subtitle: "Ma stratégie personnelle",
    to: "/strategy",
  },
  {
    title:
      "Tu vas faire quoi si tu prends ta retraite à 45 ans ? Tu ne vas pas t'ennuyer ?",
    subtitle: "Ma stratégie personnelle",
    to: "/strategy",
  },
  {
    title:
      "Comment tu fais pour mettre 2/3 de tes revenus de côté chaque mois ? Tu ne dépenses rien ?",
    subtitle: "Ma stratégie personnelle",
    to: "/strategy",
  },
  {
    title:
      "Tu investis en bourse mais tu payes un loyer, tu ne perds pas de l'argent ?",
    subtitle: "Ma stratégie personnelle",
    to: "/strategy",
  },
  {
    title:
      "Investir c'est le mal ! Tu participes au capitalisme, la pauvreté, les crises, les guerres… N'as-tu pas honte ?",
    subtitle: "Ma stratégie personnelle",
    to: "/strategy",
  },
  { title: "Work in Progress", subtitle: "Optimisation fiscale", to: "/taxes" },
  {
    title: "Work in Progress",
    subtitle: "Comparateur d'Enveloppes Fiscales",
    to: "/tax-wrapper-comparator",
  },
  { title: "Calcul d'intérêts composés", subtitle: "Outils", to: "/tools" },
  { title: "Calcul de prêt", subtitle: "Outils", to: "/tools" },
  { title: "Louer ou Acheter ?", subtitle: "Outils", to: "/tools" },
  {
    title: "Comparateur d'Enveloppes Fiscales",
    subtitle: "Outils",
    to: "/tools",
  },
  { title: "Profil de risque", subtitle: "Outils", to: "/tools" },
  {
    title: "Bases du Trading",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
  {
    title: "Trading vs Investissement",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
  {
    title: "Réalité du trading et institutions",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
  {
    title: "Les marchés financiers",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
  {
    title: "Plateformes de trading",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
  { title: "Day Trading", subtitle: "Les bases du trading", to: "/trading" },
  { title: "Swing Trading", subtitle: "Les bases du trading", to: "/trading" },
  { title: "Scalping", subtitle: "Les bases du trading", to: "/trading" },
  {
    title: "Position Trading",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
  {
    title: "Algorithmic Trading",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
  { title: "Position Long", subtitle: "Les bases du trading", to: "/trading" },
  {
    title: "Position Short (vente à découvert)",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
  {
    title: "Les chandeliers japonais",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
  {
    title: "Stratégies et gestion du risque",
    subtitle: "Les bases du trading",
    to: "/trading",
  },
];
